name = "DelayMaps"
uuid = "4cb80704-4037-41ba-916a-d1b42d90ccfb"
authors = ["Adam Zaidan <adam.zaidan@gatech.edu>"]
version = "1.0.0-DEV"

[deps]
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
RadiiPolynomial = "f2081a94-c849-46b6-8dc9-07bb90ed72a9"

[compat]
IntervalArithmetic = "0.22.19"
RadiiPolynomial = "0.8.15"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
